// Post-build prerender: launches headless Chromium against a tiny static SPA
// server pointed at dist/, navigates each route, and writes the post-hydration
// HTML to dist/<route>/index.html. Vercel will serve those static files
// directly, so crawlers (Googlebot, GPTBot, ClaudeBot, PerplexityBot) see
// fully-rendered content without executing JavaScript.
//
// Cross-environment Chromium strategy:
//   - On Vercel build (`VERCEL=1`): use @sparticuz/chromium (stripped binary
//     that ships its own libnspr4 etc., works in Vercel's bare container)
//   - Locally on macOS: use installed Google Chrome (`/Applications/...`)
//   - Locally on Linux: probe well-known chromium / google-chrome paths
//
// Why not full puppeteer: bundles ~150MB of Chromium that fails on Vercel's
// build container with "libnspr4.so: cannot open shared object file".

import puppeteer from 'puppeteer-core'
import chromium from '@sparticuz/chromium'
import { createServer } from 'node:http'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync, readFileSync } from 'node:fs'
import { resolve, join, dirname, extname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { verifyNavigation } from './navigation-smoke.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DIST = resolve(__dirname, '..', 'dist')
// Trilingual URL routing — base routes per locale + the root redirect +
// one route per article slug per locale. Locales kept in a single source of
// truth so adding a fourth language is a one-line change.
const LOCALES = ['en', 'pt', 'es']
const PAGE_PATHS = ['', '/why-avante', '/library', '/portfolio', '/investors', '/principles']
// Article slugs are derived from the single source of truth, src/app/data/articles.ts,
// so every article (hand-written or generated by content-engine/merge.py) is
// prerendered automatically. No hardcoded list to keep in sync. The data file mixes
// TS object literals (slug: 'x') and the engine's JSON region ("slug": "x"), so the
// pattern matches both quoting styles. Dedupe to be safe.
const ARTICLE_SLUGS = (() => {
  const src = readFileSync(resolve(__dirname, '..', 'src', 'app', 'data', 'articles.ts'), 'utf8')
  const slugs = new Set()
  for (const m of src.matchAll(/['"]?slug['"]?\s*:\s*['"]([a-z0-9][a-z0-9-]*)['"]/g)) {
    slugs.add(m[1])
  }
  const list = [...slugs]
  if (list.length === 0) throw new Error('prerender: no article slugs found in articles.ts')
  return list
})()
const BASE_ROUTES = [
  '/',
  ...LOCALES.flatMap((loc) => PAGE_PATHS.map((p) => `/${loc}${p}`)),
  '/preview/heroes', // internal preview, noindex via meta robots
]
const ARTICLE_ROUTES = LOCALES.flatMap((loc) =>
  ARTICLE_SLUGS.map((slug) => `/${loc}/library/${slug}`)
)
const ROUTES = [...BASE_ROUTES, ...ARTICLE_ROUTES]
const PORT = 4179

// ─────────────────────────────────────────────────────────────────────
// Resolve a Chromium binary path that works in this environment
// ─────────────────────────────────────────────────────────────────────

const KNOWN_LOCAL_PATHS = [
  // macOS
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',
  // Linux
  '/usr/bin/google-chrome',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium',
  '/usr/bin/chromium-browser',
  '/snap/bin/chromium',
]

async function resolveChromium() {
  // Vercel / generic CI: use Sparticuz
  if (process.env.VERCEL || process.env.CI) {
    return {
      executablePath: await chromium.executablePath(),
      args: chromium.args,
      headless: chromium.headless,
    }
  }

  // Local: probe known install paths
  for (const path of KNOWN_LOCAL_PATHS) {
    if (existsSync(path)) {
      return {
        executablePath: path,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        headless: true,
      }
    }
  }

  throw new Error(
    'No Chromium binary found at known paths. Install Google Chrome ' +
    'locally, or set VERCEL=1 to use @sparticuz/chromium.'
  )
}

// ─────────────────────────────────────────────────────────────────────
// Tiny SPA static server: SPA fallback so React Router takes over for
// extension-less paths (matches Vercel rewrite contract).
// ─────────────────────────────────────────────────────────────────────

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.json': 'application/json',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.txt':  'text/plain; charset=utf-8',
  '.xml':  'application/xml',
  '.webmanifest': 'application/manifest+json',
}

function makeServer() {
  return createServer(async (req, res) => {
    const urlPath = decodeURIComponent(req.url.split('?')[0])
    let filePath = join(DIST, urlPath === '/' ? 'index.html' : urlPath)

    // Extension-less paths are app routes and always get the SPA shell. A
    // route's folder can already exist on disk (a child route was written
    // first), so its existence must not turn the request into a file read.
    if (!extname(filePath)) {
      filePath = join(DIST, 'index.html')
    } else if (!existsSync(filePath)) {
      res.writeHead(404)
      return res.end('404')
    }

    try {
      const data = await readFile(filePath)
      const ext = extname(filePath).toLowerCase()
      res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' })
      res.end(data)
    } catch (err) {
      res.writeHead(500)
      res.end(String(err))
    }
  })
}

// ─────────────────────────────────────────────────────────────────────
// Pipeline
// ─────────────────────────────────────────────────────────────────────

const launchOpts = await resolveChromium()
console.log(`🌐 Chromium: ${launchOpts.executablePath}`)

const server = makeServer()
await new Promise((r) => server.listen(PORT, r))
console.log(`📡 Static server on http://localhost:${PORT}`)

const browser = await puppeteer.launch(launchOpts)

try {
  await verifyNavigation(browser, `http://localhost:${PORT}`)
} catch (error) {
  await browser.close()
  server.close()
  throw error
}

const errors = []

// Render a single route with up to 2 attempts. Vercel's Sparticuz Chromium
// is slower than local Chrome and occasionally trips the hydration sentinel.
// One retry on a fresh page is enough — true hangs don't recover.
async function renderRoute(route) {
  for (let attempt = 1; attempt <= 2; attempt++) {
    const page = await browser.newPage()
    try {
      await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 })
      page.on('pageerror', (e) => errors.push({ route, err: String(e) }))

      const url = `http://localhost:${PORT}${route}`
      await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 })

      // Wait until the page itself has rendered, not only the app shell: every
      // route ends up with an <h1> and the <footer>. Elapsed time is not a safe
      // signal once several tabs share the CPU. An error page also ends the
      // wait, and is rejected just below. 30s tolerates Vercel build's slower
      // Chromium + lazy chunk loads on first nav.
      await page.waitForFunction(
        () => {
          const root = document.getElementById('root')
          if (!root) return false
          if (root.querySelector('[data-route-error]')) return true
          if (root.querySelector('h2')?.textContent?.includes('Unexpected Application Error')) return true
          return Boolean(root.querySelector('h1') && root.querySelector('footer'))
        },
        { timeout: 30000 }
      )

      // Settle window for lazy effects (Framer Motion poses, etc.)
      await new Promise((r) => setTimeout(r, 500))

      const routeError = await page.evaluate(() => Boolean(document.querySelector('[data-route-error]')) ||
        document.querySelector('#root h2')?.textContent?.includes('Unexpected Application Error'))
      if (routeError) throw new Error('Route rendered an application error instead of page content')

      const html = await page.content()

      const outDir = route === '/' ? DIST : join(DIST, route)
      if (route !== '/') await mkdir(outDir, { recursive: true })
      const outFile = join(outDir, 'index.html')
      await writeFile(outFile, html)

      const sizeKB = (Buffer.byteLength(html) / 1024).toFixed(1)
      console.log(`  ✓ ${outFile.replace(DIST, 'dist')}  (${sizeKB} KB)`)
      return // success
    } catch (err) {
      const tag = attempt === 1 ? 'retry' : 'FAILED'
      console.log(`  ${attempt === 1 ? '↻' : '✗'} ${tag} ${route}: ${err.message}`)
      if (attempt === 2) errors.push({ route, err: String(err) })
    } finally {
      await page.close()
    }
  }
}

// '/' renders first and alone: it overwrites dist/index.html, the shell the
// static server hands to every other route, so they must all start from it.
// The rest render on a fixed number of tabs in parallel.
const CONCURRENCY = Math.max(1, Number(process.env.PRERENDER_CONCURRENCY) || 6)
const startedAt = Date.now()
console.log('→ Rendering /')
await renderRoute('/')

const queue = ROUTES.filter((route) => route !== '/')
console.log(`→ Rendering ${queue.length} routes, ${CONCURRENCY} at a time`)
await Promise.all(
  Array.from({ length: CONCURRENCY }, async () => {
    while (queue.length) await renderRoute(queue.shift())
  })
)

await browser.close()
server.close()

if (errors.length) {
  console.error('\n❌ Errors during prerender:')
  for (const e of errors) console.error(`  ${e.route}: ${e.err}`)
  process.exit(1)
}

const seconds = Math.round((Date.now() - startedAt) / 1000)
console.log(`\n✅ Prerender complete: ${ROUTES.length} routes in ${seconds}s.`)
